config/routes.rb
Rails.application.routes.draw do
  
  root 'main#index'

  resources :main
  resources :users
  resources :users do
    member do
      post :load
    end
  end
  
  
  resource :session, :only => [:new, :create, :destroy]
  get '/login' => "sessions#new", :as => "login"
  delete '/logout' => "sessions#destroy", :as => "logout"
  
  resource :software, :only => [:show]
  resource :documentation, :only => [:show]
  resource :etabs2_steel_manuals, :only => [:show]
  resource :etabs2_steel_online_manuals, :only => [:show]
  resource :etabs_vs_steel_pushover_papers, :only => [:show]
  resource :about, :only => [:show]
  
  
  resources :profiles
  resources :defaults
  resources :model_informations
  resources :analysis_options
  resources :convergence_options
  
  resources :fiber_options
  resources :nsefbr_fibers
  resources :nsefbc_fibers
  
  resources :vertical_constraint_options
  resources :vertical_constraints
  
  resources :load_options

  resources :response_time_history_options
  resources :extra_time_histories
  
  resources :material_models
  
  resources :foundation_node_options
  resources :foundation_nodes
  
  
  resources :models do
    resources :analyses do
      member do
        post :submit
      end
      resources :defaults do
        resources :model_informations
        resources :analysis_options
        resources :convergence_options
        resources :fiber_options do
          resources :nsefbr_fibers
          resources :nsefbc_fibers
        end
        resources :vertical_constraint_options do
          resources :vertical_constraints
        end
        resources :load_options
        resources :response_time_history_options do
          resources :extra_time_histories
        end
        resources :material_models
        resources :foundation_node_options do
          resources :foundation_nodes
        end
      end
    end
  end

end

app/models/analysis.rb
class Analysis < ActiveRecord::Base
  belongs_to :user
  
  has_one :default, as: :config, dependent: :destroy  
end

app/models/analysis_option.rb
class AnalysisOption < ActiveRecord::Base
  #Dependencies
  belongs_to :default
end

app/models/convergence_option.rb
class ConvergenceOption < ActiveRecord::Base
  belongs_to :default
end

app/models/default.rb
class Default < ActiveRecord::Base
  belongs_to :config, polymorphic: true
  
  has_one :model_information, dependent: :destroy
  has_one :analysis_option, dependent: :destroy
  has_one :convergence_option, dependent: :destroy
  
  has_one :fiber_option, dependent: :destroy
  has_many :nsefbc_fiber, :through => :fiber_option
  has_many :nsefbr_fiber, :through => :fiber_option
  
  has_one :vertical_constraint_option, dependent: :destroy
  has_many :vertical_constraint, :through => :vertical_constraint_option
  
  has_one :load_option, dependent: :destroy
  
  has_one :response_time_history_option, dependent: :destroy
  has_many :extra_time_history, :through => :response_time_history_option
  
  has_one :material_model, dependent: :destroy
  
  has_one :foundation_node_option, dependent: :destroy
  has_many :foundation_nodes, :through => :foundation_node_option
end

app/models/fiber_option.rb
class FiberOption < ActiveRecord::Base
  belongs_to :default
  has_many :nsefbc_fibers, dependent: :destroy
  has_many :nsefbr_fibers, dependent: :destroy
end

app/models/floor.rb
class Floor < ActiveRecord::Base
end

app/models/foundation_node.rb
class FoundationNode < ActiveRecord::Base
  belongs_to :foundation_node_option
end

app/models/load_combo.rb
class LoadCombo < ActiveRecord::Base
  belongs_to :model
end

app/models/load_option.rb
class LoadOption < ActiveRecord::Base
  belongs_to :default
end

app/models/material_model.rb
class MaterialModel < ActiveRecord::Base
  belongs_to :default
end

app/models/model.rb
class Model < ActiveRecord::Base
  #Callbacks
  after_create :parse_file
  after_destroy :cleanup
  
  #Dependencies
  belongs_to :user

  has_many :floors, dependent: :destroy
  has_many :points, dependent: :destroy
  has_many :nodes, dependent: :destroy
  has_many :load_combos, dependent: :destroy
  
  has_many :analyses, dependent: :destroy
  
  
  private
    def cleanup
      #Cleanup Floors, Points, Nodes, and Load Combos
      self.floors.destroy
      self.points.destroy
      self.nodes.destroy
      self.load_combos.destroy
    end
  
  
    def parse_file
      #Parse through the file
      File.open(File.join(Rails.root,'public',self.user_id.to_s,self.name,self.e2k_file)).each do |line|
        #Check for Floors
        if /^\s+STORY\s+\"(.+)\"\s+(\w+)\s+([^\s]+).+/.match(line)
          floor = Floor.new(:model_id => self.id, :name => $1, :elevation => $3)
          floor.model_id = self.id
          floor.save
        end
        
        #Check for Points
        if /^\s+POINT\s+\"(\d+)\"\s+([^\s]+)\s([^\s]+)/.match(line)
          point = Point.new(:model_id => self.id, :name => $1, :X => $2, :Y => $3)
          point.model_id = self.id
          point.save
        end
          
        #Check for Nodes
        if /\s+POINTASSIGN\s+\"(\d+)\"\s+\"(\w+)\".+/.match(line)
          node = Node.new(:model_id => self.id, :point_name => $1, :floor_name => $2)
          node.model_id = self.id
          
          #Get X, Y, and Z Coords
          node.X = self.points.where(name: $1).first.X
          node.Y = self.points.where(name: $1).first.Y
          node.Z = self.floors.where(name: $2).first.elevation
          node.save
        end
          
        #Check for Load Combos
        if /\s+COMBO\s\"(.+)\"\s+TYPE\s+\"(.+)\"\s*(SF)?\s*(.+)?/.match(line)
          load_combo = LoadCombo.new(:model_id => self.id, :case_name => $1)
          load_combo.model_id = self.id
          load_combo.save
        end
      end
    end
end

app/models/node.rb
class Node < ActiveRecord::Base
  belongs_to :model
end

app/models/nsefbc_fiber.rb
class NsefbcFiber < ActiveRecord::Base
  belongs_to :Fiber_Option
end

app/models/nsefbr_fiber.rb
class NsefbrFiber < ActiveRecord::Base
  belongs_to :Fiber_Option
end

app/models/point.rb
class Point < ActiveRecord::Base
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  #Dependencies
  belongs_to :user
  
  has_many :defaults, as: :config, dependent: :destroy  
end

app/models/user.rb
require 'digest'

class User < ActiveRecord::Base  
  #Dependencies
  has_one :profile, dependent: :destroy

  
  has_many :defaults, :through => :profile, :source => :config, :source_type => "Profile"

  
  has_many :models, dependent: :destroy
  
  
  
  #Validation
  validates_uniqueness_of :email
  validates_length_of :email, :within => 5..50
  validates_format_of :email, :multiline => true, :with =>  /^[^@][\w.-]+@[\w.-]+[.][a-z]{2,4}$/i
  
  validates_confirmation_of :password
  validates_length_of :password, :within => 4..20
  validates_presence_of :password, :if => :password_required?
  
  #Callbacks
  before_save :encrypt_new_password
  
  #Methods
  attr_accessor :password
  
  def self.authenticate(email, password)
    user = find_by_email(email)
    return user if user && user.authenticated?(password)
  end
  
  def authenticated?(password)
    self.hashed_password == encrypt(password)
  end
	
	protected
	  def encrypt_new_password
	    return if password.blank?
	    self.hashed_password = encrypt(password)
	  end
	  
	  def password_required?
	    hashed_password.blank? || password.present?
	  end
	  
	  def encrypt(string)
	    Digest::SHA1.hexdigest(string)
	  end
end

app/controllers/convergence_options_controller.rb
class ConvergenceOptionsController < ApplicationController
  #Callbacks
  before_action :authenticate, except: [:index, :show]
  
  #Methods
  def show
    @convergence_option = current_default.convergence_option
  end
  
  def new
    @convergence_option = Convergence_Option.new
  end
  
  def edit
    @convergence_option = current_default.convergence_option
  end
  
  def update
    @convergence_option = current_default.convergence_option
    
    if @convergence_option.update(convergence_option_params)
      
      if (params[:analysis_id] == nil)
        save_path =  convergence_option_path(@convergence_option.id)
      else
        save_path = model_analysis_default_convergence_option_path(current_model.id, current_analysis.id, current_default.id, @convergence_option.id)
      end
      
      redirect_to save_path, :notice => "Convergence Options Updated Sucessfully"
    else
      render :edit
    end
  end
  
  def destroy
  end
  
  private
    def convergence_option_params
      params.require(:convergence_option).permit(:mig, :tol1, :tol3, :tol5, :tol7, :alphac, :a3)
    end  
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/convergence_options_helper.rb
module ConvergenceOptionsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/models_helper.rb
module ModelsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/convergence_options/edit.html.erb
<% if params[:analysis_id] == nil %>
	<% save_path = convergence_option_path(@convergence_option.id) %>	
<% else %>
	<% save_path = model_analysis_default_convergence_option_path(current_model.id, current_analysis.id, current_default.id, @convergence_option.id) %>
<% end %>

<div class="container-fluid">
	<div class="row">
		<div class="col-md-2 sidebar">
			<%= render :partial =>  "shared/nav" %>
		</div>

		<div class="col-md-10 col-md-offset-2 main">
			<%= form_for @convergence_option do |f| %>				
				<div>
					<%= f.label "Maximum number of global iterations (MIG):" %>
					<%= f.text_field :mig %>
				</div> 
				<div>
					<%= f.label "Force Tolerance for Global Iterations (TOL1):" %>
					<%= f.text_field :tol1 %>
				</div> 
				<div> 
					<%= f.label "Moment Tolerance for Global Iterations (TOL3):" %>
					<%= f.text_field :tol3 %>
				</div> 
				<div> 
					<%= f.label "Force Tolerance for Local Iterations (TOL5):" %>
					<%= f.text_field :tol5 %>
				</div> 
				<div> 
					<%= f.label "Moment Tolerance for Local Iterations (TOL7):" %>
					<%= f.text_field :tol7 %>
				</div>  
				<div>
					<%= f.label "Connection Element Stiffness (ALPHAC):" %>
					<%= f.text_field :alphac %>
				</div> 
				<div>
					<%= f.label "Multiplier of yield strength of Floor-to-Floor springs to give Yield Strength of Floor-to-Floor Shear Dampers (A3):" %>
					<%= f.text_field :a3 %> 
				</div> 
				
				<% if params[:analysis_id] != nil %>
					<!-- Set some param values -->
					<%= hidden_field_tag :model_id, params[:model_id] %>
					<%= hidden_field_tag :analysis_id, params[:analysis_id] %>
					<%= hidden_field_tag :default_id, params[:default_id] %>
				<% end %>
				
				<div class="action">
					<%= button_to "Save", save_path %>
				</div>
			<% end %>	
		</div>
	</div> 
</div>

app/views/convergence_options/show.html.erb
<% if params[:analysis_id] == nil %>
	<% edit_path = edit_convergence_option_path(@convergence_option.id) %>
	<% prev_path = analysis_option_path(current_default.analysis_option.id)%>
	<% next_path = fiber_option_path(current_default.fiber_option.id)%>
<% else %>
	<% edit_path = edit_model_analysis_default_convergence_option_path(current_model.id, current_analysis.id, current_default.id, @convergence_option.id) %>
	<% prev_path = model_analysis_default_analysis_option_path(current_model.id, current_analysis.id, current_default.id, current_default.analysis_option.id) %>
	<% next_path = model_analysis_default_fiber_option_path(current_model.id, current_analysis.id, current_default.id, current_default.fiber_option.id) %>
<% end %>

<div class="container-fluid">
	<div class="row">
		<div class="col-md-2 sidebar">
			<%= render :partial => "shared/nav" %>
		</div>
		<div class="col-md-10 col-md-offset-2 main">
			<h3>Convergence Options</h3>
			<div class="field">
				<p>Maximum number of global iterations (MIG): <%= @convergence_option.mig %></p>
				<p>Force Tolerance for Global Iterations (TOL1): <%= @convergence_option.tol1 %></p>
				<p>Moment Tolerance for Global Iterations (TOL3): <%= @convergence_option.tol3 %></p>
				<p>Force Tolerance for Local Iterations (TOL5): <%= @convergence_option.tol5 %></p>
				<p>Moment Tolerance for Local Iterations (TOL7): <%= @convergence_option.tol7 %></p>
				<span class="has-tooltip" data-toggle="tooltip" title="<%= "Default stiffness for vertical connection elements" %>">
					<p>Connection Element Stiffness (ALPHAC): <%= @convergence_option.alphac %></p>
				</span>
				<span class="has-tooltip" data-toggle="tooltip" title="<%= "For more information view the written manual" %>">
					<p>Multiplier of yield strength of Floor-to-Floor springs to give Yield Strength of Floor-to-Floor Shear Dampers (A3): <%= @convergence_option.a3 %></p>
				</span>
			</div>
			<div class="action">
				<%= link_to "edit", edit_path %>
			</div>
			<%= button_to "Previous",  prev_path, :method => :get%>
			<%= button_to "Next", next_path, :method => :get%>
		</div>
	</div> 
</div>