config/routes.rb
Rails.application.routes.draw do
  
  root 'main#index'

  resources :main
  resources :users
  resources :users do
    member do
      post :load
    end
  end
  
  
  resource :session, :only => [:new, :create, :destroy]
  get '/login' => "sessions#new", :as => "login"
  delete '/logout' => "sessions#destroy", :as => "logout"
  
  resource :software, :only => [:show]
  resource :documentation, :only => [:show]
  resource :etabs2_steel_manuals, :only => [:show]
  resource :etabs2_steel_online_manuals, :only => [:show]
  resource :etabs_vs_steel_pushover_papers, :only => [:show]
  resource :about, :only => [:show]
  
  
  resources :profiles
  resources :defaults
  resources :model_informations
  resources :analysis_options
  resources :convergence_options
  
  resources :fiber_options
  resources :nsefbr_fibers
  resources :nsefbc_fibers
  
  resources :vertical_constraint_options
  resources :vertical_constraints
  
  resources :load_options

  resources :response_time_history_options
  resources :extra_time_histories
  
  resources :material_models
  
  resources :foundation_node_options
  resources :foundation_nodes
  
  
  resources :models do
    resources :analyses do
      member do
        post :submit
      end
      resources :defaults do
        resources :model_informations
        resources :analysis_options
        resources :convergence_options
        resources :fiber_options do
          resources :nsefbr_fibers
          resources :nsefbc_fibers
        end
        resources :vertical_constraint_options do
          resources :vertical_constraints
        end
        resources :load_options
        resources :response_time_history_options do
          resources :extra_time_histories
        end
        resources :material_models
        resources :foundation_node_options do
          resources :foundation_nodes
        end
      end
    end
  end

end

app/models/foundation_node_option.rb
class FoundationNodeOption < ActiveRecord::Base
  belongs_to :default
  has_many :foundation_nodes, dependent: :destroy
end

app/controllers/foundation_node_options_controller.rb
class FoundationNodeOptionsController < ApplicationController
  #Callbacks
  before_action :authenticate, except: [:index, :show]
  
  #Methods
  def show
    @foundation_node_option = current_default.foundation_node_option
  end
  
  def new
    @foundation_node_option = Foundation_Node_Option.new
  end
  
  def edit
    @foundation_node_option = current_default.foundation_node_option
  end
  
  def update
    @foundation_node_option = current_default.foundation_node_option
    
    if @foundation_node_option.update(foundation_node_option_params)
      
      if (params[:analysis_id] == nil)
        save_path =  foundation_node_option_path(@foundation_node_option.id)
      else
        save_path = model_analysis_default_foundation_node_option_path(current_model.id, current_analysis.id, current_default.id, @foundation_node_option.id)
      end
      
      redirect_to save_path, :notice => "Foundation Node Options have been Updated Sucessfully"
    else
      render :edit
    end
  end
  
  def destroy
  end
  
  private
    def foundation_node_option_params
      params.require(:foundation_node_option).permit(:ALP, :STRH, :STRVU, :STRVD)
    end 
end

app/helpers/foundation_node_options_helper.rb
module FoundationNodeOptionsHelper
end

app/views/foundation_node_options/edit.html.erb
<% if params[:analysis_id] == nil %>
	<% save_path = foundation_node_option_path(current_default.foundation_node_option.id) %>	
<% else %>
	<% save_path = model_analysis_default_foundation_node_option_path(current_model.id, current_analysis.id, current_default.id, current_default.foundation_node_option.id) %>
<% end %>

<div class="container-fluid">
	<div class="row">
		<div class="col-md-2 sidebar">
			<%= render :partial =>  "shared/nav" %>
		</div>

		<div class="col-md-10 col-md-offset-2 main">
			<%= form_for @foundation_node_option do |f| %>				
				<h3>Foundation Node Options</h3>
				<h4>Default Foundation Node</h4>
				<div class="table-responsive">
					<table class="table table-striped">
				    	<thead>
							<tr>
				                <th>Post-Yield Stiffness Ratio for Foundation Springs (ALP)</th>
				                <th>Yield Strength of Horizontal Spring (STRH)</th>
								<th>Yield Strength of Vertical Spring in Upward Direction (STRVU)</th>
								<th>Yield Strength of Vertical Spring in Downward Direction (STRVD)
				            </tr>
				        </thead>
				        <tbody>
							<tr>
				                <td><%= f.text_field :ALP %></td>
								<td><%= f.text_field :STRH %></td>
								<td><%= f.text_field :STRVU %></td>
								<td><%= f.text_field :STRVD %></td>
				            </tr>
				        </tbody>
				    </table>
				</div>
					
				<% if params[:analysis_id] != nil %>
					<!-- Set some param values -->
					<%= hidden_field_tag :model_id, params[:model_id] %>
					<%= hidden_field_tag :analysis_id, params[:analysis_id] %>
					<%= hidden_field_tag :default_id, params[:default_id] %>
				<% end %>	
					
				<div class="action">
					<%= button_to "Save", save_path %>
				</div>
			<% end %>	
		</div>
	</div> 
</div>

app/views/foundation_node_options/show.html.erb
<% if params[:analysis_id] == nil %>
	<% edit_path = edit_foundation_node_option_path(@foundation_node_option.id) %>
	<% prev_path = material_model_path(current_default.material_model.id)%>
	<% new_node_path = new_foundation_node_path %>
<% else %>
	<% edit_path = edit_model_analysis_default_foundation_node_option_path(current_model.id, current_analysis.id, current_default.id, @foundation_node_option.id) %>
	<% prev_path = model_analysis_default_material_model_path(current_model.id, current_analysis.id, current_default.id, current_default.material_model.id) %>
	<% new_node_path = new_model_analysis_default_foundation_node_option_foundation_node_path(current_model.id, current_analysis.id, current_default.id, @foundation_node_option.id)%>
<% end %>

<div class="container-fluid">
	<div class="row">
		<div class="col-md-2 sidebar">
			<%= render :partial => "shared/nav" %>
		</div>
		<div class="col-md-10 col-md-offset-2 main">
			<h3>Foundation Node Options</h3>
			<div class="action">
				<%= link_to "edit", edit_path %>
			</div>
			<h4>Default Foundation Node</h4>
			<div class="table-responsive">
				<table class="table table-striped">
			    	<thead>
						<tr>
			                <th>Post-Yield Stiffness Ratio for Foundation Springs (ALP)</th>
			                <th>Yield Strength of Horizontal Spring (STRH)</th>
							<th>Yield Strength of Vertical Spring in Upward Direction (STRVU)</th>
							<th>Yield Strength of Vertical Spring in Downward Direction (STRVD)
			            </tr>
			        </thead>
			        <tbody>
						<tr>
			                <td><%= @foundation_node_option.ALP %></td>
							<td><%= @foundation_node_option.STRH %></td>
							<td><%= @foundation_node_option.STRVU %></td>
							<td><%= @foundation_node_option.STRVD %></td>
			            </tr>
			        </tbody>
			    </table>
			</div>
			
			<h4>Specific Foundation Nodes</h4>
			<%= button_to "New", new_node_path, :method => :get %>
			<div class="table-responsive">
				<table class="table table-striped">
			    	<thead>
						<tr>
							<th>ETABS Spring Element Name
			                <th>Post-Yield Stiffness Ratio for Foundation Springs (ALP)</th>
			                <th>Yield Strength of Horizontal Spring (STRH)</th>
							<th>Yield Strength of Vertical Spring in Upward Direction (STRVU)</th>
							<th>Yield Strength of Vertical Spring in Downward Direction (STRVD)
			            </tr>
			        </thead>
			        <tbody>
						<% @foundation_node_option.foundation_nodes.each do |fn| %>
							<% if params[:analysis_id] == nil %>
								<% edit_node_path = edit_foundation_node_path(fn.id) %>
								<% delete_node_path = foundation_node_path(fn.id) %>								
							<% else %>
								<% edit_node_path = edit_model_analysis_default_foundation_node_option_foundation_node_path(current_model.id, current_analysis.id, current_default.id, @foundation_node_option.id, fn.id) %>
								<% delete_node_path = model_analysis_default_foundation_node_option_foundation_node_path(current_model.id, current_analysis.id, current_default.id, @foundation_node_option.id, fn.id) %>
							<% end%>
							<tr>
			                	<td><%= fn.name %></td>
								<td><%= fn.ALP %></td>
								<td><%= fn.STRH %></td>
								<td><%= fn.STRVU %></td>
								<td><%= fn.STRVD %></td>
								<td><%= button_to "Edit", edit_node_path, :method => :get %></td>
								<td><%= button_to "Delete", delete_node_path, method: :delete %></td>
			                </tr>
			            <% end %>
			        </tbody>
			    </table>
			</div>
			<%= button_to "Previous", prev_path, :method => :get%>
		</div>
	</div> 
</div>