config/routes.rb
Rails.application.routes.draw do
  
  root 'main#index'

  resources :main
  resources :users
  resources :users do
    member do
      post :load
    end
  end
  
  
  resource :session, :only => [:new, :create, :destroy]
  get '/login' => "sessions#new", :as => "login"
  delete '/logout' => "sessions#destroy", :as => "logout"
  
  resource :software, :only => [:show]
  resource :documentation, :only => [:show]
  resource :etabs2_steel_manuals, :only => [:show]
  resource :etabs2_steel_online_manuals, :only => [:show]
  resource :etabs_vs_steel_pushover_papers, :only => [:show]
  resource :about, :only => [:show]
  
  
  resources :profiles
  resources :defaults
  resources :model_informations
  resources :analysis_options
  resources :convergence_options
  
  resources :fiber_options
  resources :nsefbr_fibers
  resources :nsefbc_fibers
  
  resources :vertical_constraint_options
  resources :vertical_constraints
  
  resources :load_options

  resources :response_time_history_options
  resources :extra_time_histories
  
  resources :material_models
  
  resources :foundation_node_options
  resources :foundation_nodes
  
  
  resources :models do
    resources :analyses do
      member do
        post :submit
      end
      resources :defaults do
        resources :model_informations
        resources :analysis_options
        resources :convergence_options
        resources :fiber_options do
          resources :nsefbr_fibers
          resources :nsefbc_fibers
        end
        resources :vertical_constraint_options do
          resources :vertical_constraints
        end
        resources :load_options
        resources :response_time_history_options do
          resources :extra_time_histories
        end
        resources :material_models
        resources :foundation_node_options do
          resources :foundation_nodes
        end
      end
    end
  end

end

app/models/analysis.rb
class Analysis < ActiveRecord::Base
  belongs_to :user
  
  has_one :default, as: :config, dependent: :destroy  
end

app/models/analysis_option.rb
class AnalysisOption < ActiveRecord::Base
  #Dependencies
  belongs_to :default
end

app/models/default.rb
class Default < ActiveRecord::Base
  belongs_to :config, polymorphic: true
  
  has_one :model_information, dependent: :destroy
  has_one :analysis_option, dependent: :destroy
  has_one :convergence_option, dependent: :destroy
  
  has_one :fiber_option, dependent: :destroy
  has_many :nsefbc_fiber, :through => :fiber_option
  has_many :nsefbr_fiber, :through => :fiber_option
  
  has_one :vertical_constraint_option, dependent: :destroy
  has_many :vertical_constraint, :through => :vertical_constraint_option
  
  has_one :load_option, dependent: :destroy
  
  has_one :response_time_history_option, dependent: :destroy
  has_many :extra_time_history, :through => :response_time_history_option
  
  has_one :material_model, dependent: :destroy
  
  has_one :foundation_node_option, dependent: :destroy
  has_many :foundation_nodes, :through => :foundation_node_option
end

app/models/fiber_option.rb
class FiberOption < ActiveRecord::Base
  belongs_to :default
  has_many :nsefbc_fibers, dependent: :destroy
  has_many :nsefbr_fibers, dependent: :destroy
end

app/models/floor.rb
class Floor < ActiveRecord::Base
end

app/models/foundation_node.rb
class FoundationNode < ActiveRecord::Base
  belongs_to :foundation_node_option
end

app/models/load_combo.rb
class LoadCombo < ActiveRecord::Base
  belongs_to :model
end

app/models/load_option.rb
class LoadOption < ActiveRecord::Base
  belongs_to :default
end

app/models/material_model.rb
class MaterialModel < ActiveRecord::Base
  belongs_to :default
end

app/models/model.rb
class Model < ActiveRecord::Base
  #Callbacks
  after_create :parse_file
  after_destroy :cleanup
  
  #Dependencies
  belongs_to :user

  has_many :floors, dependent: :destroy
  has_many :points, dependent: :destroy
  has_many :nodes, dependent: :destroy
  has_many :load_combos, dependent: :destroy
  
  has_many :analyses, dependent: :destroy
  
  
  private
    def cleanup
      #Cleanup Floors, Points, Nodes, and Load Combos
      self.floors.destroy
      self.points.destroy
      self.nodes.destroy
      self.load_combos.destroy
    end
  
  
    def parse_file
      #Parse through the file
      File.open(File.join(Rails.root,'public',self.user_id.to_s,self.name,self.e2k_file)).each do |line|
        #Check for Floors
        if /^\s+STORY\s+\"(.+)\"\s+(\w+)\s+([^\s]+).+/.match(line)
          floor = Floor.new(:model_id => self.id, :name => $1, :elevation => $3)
          floor.model_id = self.id
          floor.save
        end
        
        #Check for Points
        if /^\s+POINT\s+\"(\d+)\"\s+([^\s]+)\s([^\s]+)/.match(line)
          point = Point.new(:model_id => self.id, :name => $1, :X => $2, :Y => $3)
          point.model_id = self.id
          point.save
        end
          
        #Check for Nodes
        if /\s+POINTASSIGN\s+\"(\d+)\"\s+\"(\w+)\".+/.match(line)
          node = Node.new(:model_id => self.id, :point_name => $1, :floor_name => $2)
          node.model_id = self.id
          
          #Get X, Y, and Z Coords
          node.X = self.points.where(name: $1).first.X
          node.Y = self.points.where(name: $1).first.Y
          node.Z = self.floors.where(name: $2).first.elevation
          node.save
        end
          
        #Check for Load Combos
        if /\s+COMBO\s\"(.+)\"\s+TYPE\s+\"(.+)\"\s*(SF)?\s*(.+)?/.match(line)
          load_combo = LoadCombo.new(:model_id => self.id, :case_name => $1)
          load_combo.model_id = self.id
          load_combo.save
        end
      end
    end
end

app/models/node.rb
class Node < ActiveRecord::Base
  belongs_to :model
end

app/models/nsefbc_fiber.rb
class NsefbcFiber < ActiveRecord::Base
  belongs_to :Fiber_Option
end

app/models/nsefbr_fiber.rb
class NsefbrFiber < ActiveRecord::Base
  belongs_to :Fiber_Option
end

app/models/point.rb
class Point < ActiveRecord::Base
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  #Dependencies
  belongs_to :user
  
  has_many :defaults, as: :config, dependent: :destroy  
end

app/models/user.rb
require 'digest'

class User < ActiveRecord::Base  
  #Dependencies
  has_one :profile, dependent: :destroy

  
  has_many :defaults, :through => :profile, :source => :config, :source_type => "Profile"

  
  has_many :models, dependent: :destroy
  
  
  
  #Validation
  validates_uniqueness_of :email
  validates_length_of :email, :within => 5..50
  validates_format_of :email, :multiline => true, :with =>  /^[^@][\w.-]+@[\w.-]+[.][a-z]{2,4}$/i
  
  validates_confirmation_of :password
  validates_length_of :password, :within => 4..20
  validates_presence_of :password, :if => :password_required?
  
  #Callbacks
  before_save :encrypt_new_password
  
  #Methods
  attr_accessor :password
  
  def self.authenticate(email, password)
    user = find_by_email(email)
    return user if user && user.authenticated?(password)
  end
  
  def authenticated?(password)
    self.hashed_password == encrypt(password)
  end
	
	protected
	  def encrypt_new_password
	    return if password.blank?
	    self.hashed_password = encrypt(password)
	  end
	  
	  def password_required?
	    hashed_password.blank? || password.present?
	  end
	  
	  def encrypt(string)
	    Digest::SHA1.hexdigest(string)
	  end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/models_helper.rb
module ModelsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/shared/_nav.html.erb
<% if params[:analysis_id] == nil %>
	<ul class="nav nav-sidebar">
		<li><b>General Information</b></li>
		<li class="<%= 'active' if params[:controller] == 'users' %>"><%= link_to "Overview", user_path(current_user.id) %></li>
		<li class="<%= 'active' if params[:controller] == 'profiles' %>"><%= link_to "User Information", profile_path(current_user.profile.id) %></li>
	</ul>
	<% if (current_user.profile.active_name != nil) %>
		<% model_information_string = model_information_path(current_default.model_information.id) %>
		<% analysis_option_string = analysis_option_path(current_default.analysis_option.id) %>
		<% convergence_option_string = convergence_option_path(current_default.convergence_option.id) %>
		<% fiber_option_string = fiber_option_path(current_default.fiber_option.id) %>
		<% vertical_constraint_option_string = vertical_constraint_option_path(current_default.vertical_constraint_option.id) %>
		<% load_option_string = load_option_path(current_default.load_option.id) %>
		<% response_time_history_option_string = response_time_history_option_path(current_default.response_time_history_option.id) %>
		<% material_model_string = material_model_path(current_default.material_model.id) %>
		<% foundation_node_option_string = foundation_node_option_path(current_default.foundation_node_option.id) %>
	<% end %>
<% elsif params[:analysis_id] != nil %>
	<% model_information_string = model_analysis_default_model_information_path(current_model.id, current_analysis.id, current_default.id, current_default.model_information.id)%>
	<% analysis_option_string = model_analysis_default_analysis_option_path(current_model.id, current_analysis.id, current_default.id, current_default.analysis_option.id) %>
	<% convergence_option_string = model_analysis_default_convergence_option_path(current_model.id, current_analysis.id, current_default.id, current_default.convergence_option.id) %>
	<% fiber_option_string = model_analysis_default_fiber_option_path(current_model.id, current_analysis.id, current_default.id, current_default.fiber_option.id) %>
	<% vertical_constraint_option_string = model_analysis_default_vertical_constraint_option_path(current_model.id, current_analysis.id, current_default.id, current_default.vertical_constraint_option.id) %>
	<% load_option_string = model_analysis_default_load_option_path(current_model.id, current_analysis.id, current_default.id, current_default.load_option.id) %>
	<% response_time_history_option_string = model_analysis_default_response_time_history_option_path(current_model.id, current_analysis.id, current_default.id, current_default.response_time_history_option.id) %>
	<% material_model_string = model_analysis_default_material_model_path(current_model.id, current_analysis.id, current_default.id, current_default.material_model.id) %>
	<% foundation_node_option_string = model_analysis_default_foundation_node_option_path(current_model.id, current_analysis.id, current_default.id, current_default.foundation_node_option.id) %>
<% end %>
<ul class="nav nav-sidebar">
	<li><b>Current Default: <%= current_user.profile.active_name != nil ? current_user.profile.active_name : "None" %></b></li>
	<% if current_user.profile.active_name != nil || params[:analysis_id] != nil %>
		<li class="<%= 'active' if params[:controller] == 'model_informations' %>"><%= link_to "Model Information", model_information_string %></li>
		<li class="<%= 'active' if params[:controller] == 'analysis_options' %>"><%= link_to "Analysis Options", analysis_option_string %></li>
		<li class="<%= 'active' if params[:controller] == 'convergence_options' %>"><%= link_to "Convergence Options", convergence_option_string %></li>
		<li class="<%= 'active' if params[:controller] == 'fiber_options' %>"><%= link_to "Fiber Options", fiber_option_string %></li>
		<li class="<%= 'active' if params[:controller] == 'vertical_constraint_options' %>"><%= link_to "Vertical Constraint Options", vertical_constraint_option_string %></li>
		<li class="<%= 'active' if params[:controller] == 'load_options' %>"><%= link_to "Load Options", load_option_string %></li>
		<li class="<%= 'active' if params[:controller] == 'response_time_history_options' %>"><%= link_to "Response Time History Options", response_time_history_option_string %></li>
		<li class="<%= 'active' if params[:controller] == 'material_models' %>"><%= link_to "Material Model Options", material_model_string %></li>
		<li class="<%= 'active' if params[:controller] == 'foundation_node_options' %>"><%= link_to "Foundation Node Options", foundation_node_option_string %></li>
	<% end %>
</ul>
			

app/views/shared/_selectnode.html.erb
<div class="table-responsive">
	<table class="table table-striped">
		<thead>
			<tr>
				<th>Point Name</th>
				<th>Floor Name</th>
				<th>X</th>	
				<th>Y</th>
				<th>Z</th>
				<th>Select</th>
			</tr>
		</thead>
		<tbody>
			<% current_model.nodes.each do |node| %>
				<tr>
					<td><%= node.point_name %></td>
					<td><%= node.floor_name %></td>
					<td><%= node.X %></td>
					<td><%= node.Y %></td>
					<td><%= node.Z %></td>
					<td><%= radio_button(@model_name, local_assigns[:node_name]=="node_id" ? "node_id" : "node2_id" , node.id) %></td>
				</tr>
			<% end %>
		</tbody>
	</table>
</div>