config/routes.rb
Rails.application.routes.draw do
  
  root 'main#index'

  resources :main
  resources :users
  resources :users do
    member do
      post :load
    end
  end
  
  
  resource :session, :only => [:new, :create, :destroy]
  get '/login' => "sessions#new", :as => "login"
  delete '/logout' => "sessions#destroy", :as => "logout"
  
  resource :software, :only => [:show]
  resource :documentation, :only => [:show]
  resource :etabs2_steel_manuals, :only => [:show]
  resource :etabs2_steel_online_manuals, :only => [:show]
  resource :etabs_vs_steel_pushover_papers, :only => [:show]
  resource :about, :only => [:show]
  
  
  resources :profiles
  resources :defaults
  resources :model_informations
  resources :analysis_options
  resources :convergence_options
  
  resources :fiber_options
  resources :nsefbr_fibers
  resources :nsefbc_fibers
  
  resources :vertical_constraint_options
  resources :vertical_constraints
  
  resources :load_options

  resources :response_time_history_options
  resources :extra_time_histories
  
  resources :material_models
  
  resources :foundation_node_options
  resources :foundation_nodes
  
  
  resources :models do
    resources :analyses do
      member do
        post :submit
      end
      resources :defaults do
        resources :model_informations
        resources :analysis_options
        resources :convergence_options
        resources :fiber_options do
          resources :nsefbr_fibers
          resources :nsefbc_fibers
        end
        resources :vertical_constraint_options do
          resources :vertical_constraints
        end
        resources :load_options
        resources :response_time_history_options do
          resources :extra_time_histories
        end
        resources :material_models
        resources :foundation_node_options do
          resources :foundation_nodes
        end
      end
    end
  end

end

app/models/analysis.rb
class Analysis < ActiveRecord::Base
  belongs_to :user
  
  has_one :default, as: :config, dependent: :destroy  
end

app/models/analysis_option.rb
class AnalysisOption < ActiveRecord::Base
  #Dependencies
  belongs_to :default
end

app/models/default.rb
class Default < ActiveRecord::Base
  belongs_to :config, polymorphic: true
  
  has_one :model_information, dependent: :destroy
  has_one :analysis_option, dependent: :destroy
  has_one :convergence_option, dependent: :destroy
  
  has_one :fiber_option, dependent: :destroy
  has_many :nsefbc_fiber, :through => :fiber_option
  has_many :nsefbr_fiber, :through => :fiber_option
  
  has_one :vertical_constraint_option, dependent: :destroy
  has_many :vertical_constraint, :through => :vertical_constraint_option
  
  has_one :load_option, dependent: :destroy
  
  has_one :response_time_history_option, dependent: :destroy
  has_many :extra_time_history, :through => :response_time_history_option
  
  has_one :material_model, dependent: :destroy
  
  has_one :foundation_node_option, dependent: :destroy
  has_many :foundation_nodes, :through => :foundation_node_option
end

app/models/fiber_option.rb
class FiberOption < ActiveRecord::Base
  belongs_to :default
  has_many :nsefbc_fibers, dependent: :destroy
  has_many :nsefbr_fibers, dependent: :destroy
end

app/models/floor.rb
class Floor < ActiveRecord::Base
end

app/models/foundation_node.rb
class FoundationNode < ActiveRecord::Base
  belongs_to :foundation_node_option
end

app/models/load_combo.rb
class LoadCombo < ActiveRecord::Base
  belongs_to :model
end

app/models/load_option.rb
class LoadOption < ActiveRecord::Base
  belongs_to :default
end

app/models/material_model.rb
class MaterialModel < ActiveRecord::Base
  belongs_to :default
end

app/models/model.rb
class Model < ActiveRecord::Base
  #Callbacks
  after_create :parse_file
  after_destroy :cleanup
  
  #Dependencies
  belongs_to :user

  has_many :floors, dependent: :destroy
  has_many :points, dependent: :destroy
  has_many :nodes, dependent: :destroy
  has_many :load_combos, dependent: :destroy
  
  has_many :analyses, dependent: :destroy
  
  
  private
    def cleanup
      #Cleanup Floors, Points, Nodes, and Load Combos
      self.floors.destroy
      self.points.destroy
      self.nodes.destroy
      self.load_combos.destroy
    end
  
  
    def parse_file
      #Parse through the file
      File.open(File.join(Rails.root,'public',self.user_id.to_s,self.name,self.e2k_file)).each do |line|
        #Check for Floors
        if /^\s+STORY\s+\"(.+)\"\s+(\w+)\s+([^\s]+).+/.match(line)
          floor = Floor.new(:model_id => self.id, :name => $1, :elevation => $3)
          floor.model_id = self.id
          floor.save
        end
        
        #Check for Points
        if /^\s+POINT\s+\"(\d+)\"\s+([^\s]+)\s([^\s]+)/.match(line)
          point = Point.new(:model_id => self.id, :name => $1, :X => $2, :Y => $3)
          point.model_id = self.id
          point.save
        end
          
        #Check for Nodes
        if /\s+POINTASSIGN\s+\"(\d+)\"\s+\"(\w+)\".+/.match(line)
          node = Node.new(:model_id => self.id, :point_name => $1, :floor_name => $2)
          node.model_id = self.id
          
          #Get X, Y, and Z Coords
          node.X = self.points.where(name: $1).first.X
          node.Y = self.points.where(name: $1).first.Y
          node.Z = self.floors.where(name: $2).first.elevation
          node.save
        end
          
        #Check for Load Combos
        if /\s+COMBO\s\"(.+)\"\s+TYPE\s+\"(.+)\"\s*(SF)?\s*(.+)?/.match(line)
          load_combo = LoadCombo.new(:model_id => self.id, :case_name => $1)
          load_combo.model_id = self.id
          load_combo.save
        end
      end
    end
end

app/models/node.rb
class Node < ActiveRecord::Base
  belongs_to :model
end

app/models/nsefbc_fiber.rb
class NsefbcFiber < ActiveRecord::Base
  belongs_to :Fiber_Option
end

app/models/nsefbr_fiber.rb
class NsefbrFiber < ActiveRecord::Base
  belongs_to :Fiber_Option
end

app/models/point.rb
class Point < ActiveRecord::Base
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  #Dependencies
  belongs_to :user
  
  has_many :defaults, as: :config, dependent: :destroy  
end

app/models/user.rb
require 'digest'

class User < ActiveRecord::Base  
  #Dependencies
  has_one :profile, dependent: :destroy

  
  has_many :defaults, :through => :profile, :source => :config, :source_type => "Profile"

  
  has_many :models, dependent: :destroy
  
  
  
  #Validation
  validates_uniqueness_of :email
  validates_length_of :email, :within => 5..50
  validates_format_of :email, :multiline => true, :with =>  /^[^@][\w.-]+@[\w.-]+[.][a-z]{2,4}$/i
  
  validates_confirmation_of :password
  validates_length_of :password, :within => 4..20
  validates_presence_of :password, :if => :password_required?
  
  #Callbacks
  before_save :encrypt_new_password
  
  #Methods
  attr_accessor :password
  
  def self.authenticate(email, password)
    user = find_by_email(email)
    return user if user && user.authenticated?(password)
  end
  
  def authenticated?(password)
    self.hashed_password == encrypt(password)
  end
	
	protected
	  def encrypt_new_password
	    return if password.blank?
	    self.hashed_password = encrypt(password)
	  end
	  
	  def password_required?
	    hashed_password.blank? || password.present?
	  end
	  
	  def encrypt(string)
	    Digest::SHA1.hexdigest(string)
	  end
end

app/controllers/load_options_controller.rb
class LoadOptionsController < ApplicationController
  #Callbacks
  before_action :authenticate, except: [:index, :show]
  
  #Methods
  def show
    @load_option = current_default.load_option
  end
  
  def new
    @load_option = Load_Option.new
  end
  
  def edit
    @load_option = current_default.load_option
  end
  
  def update
    @load_option = current_default.load_option
    
    puts "here here"
    puts params
    
    if @load_option.update(load_option_params)
      
      if (params[:analysis_id] == nil)
        save_path =  load_option_path(@load_option.id)
      else
        save_path = model_analysis_default_load_option_path(current_model.id, current_analysis.id, current_default.id, @load_option.id)
      end
      
      redirect_to save_path, :notice => "Load Options Updated Sucessfully"
    else
      render :edit
    end
  end
  
  def destroy
  end
  
  private
    def load_option_params
      params.require(:load_option).permit(:load_combo, :mass_combo, :gamult)
    end 
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/analyses_helper.rb
module AnalysesHelper
end

app/helpers/load_options_helper.rb
module LoadOptionsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/models_helper.rb
module ModelsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/load_options/_loadoption_analysis.html.erb
<%= form_for @load_option do |f| %>				

	<%= f.label "Load Combination (LOADCOMBO):" %>
	<select name="load_option[load_combo]">
		<option value="">Load Combination</option>
		<% current_model.load_combos.each do |combo| %>
			<option value=<%= combo.case_name %> <%= @load_option.load_combo == combo.case_name ? "selected='selected'" : "" %> > <%= combo.case_name %> </option>
		<% end %>
	</select>


	<div>
		<%= f.label "Mass Combination (MASSCOMBO):" %>
		<select name="load_option[mass_combo]">
			<option value="">Load Combination</option>
			<% current_model.load_combos.each do |combo| %>
				<option value=<%= combo.case_name %> <%= @load_option.mass_combo == combo.case_name ? "selected='selected'" : "" %> > <%= combo.case_name %> </option>
			<% end %>
		</select>
	</div>
	
	
	<div>
		<%= f.label "Ground Acceleration Multiplier (GAMULT):" %>
		<%= f.text_field :gamult %>
	</div> 
			
	<% if params[:analysis_id] != nil %>
		<!-- Set some param values -->
		<%= hidden_field_tag :model_id, params[:model_id] %>
		<%= hidden_field_tag :analysis_id, params[:analysis_id] %>
		<%= hidden_field_tag :default_id, params[:default_id] %>
	<% end %>
			
	<div class="action">
		<%= button_to "Save", model_analysis_default_load_option_path(current_model.id, current_analysis.id, current_default.id, @load_option.id) %>
	</div>
<% end %>	

app/views/load_options/_loadoption_default.html.erb
<%= form_for @load_option do |f| %>				
	<div>
		<%= f.label "Load Combination (LOADCOMBO):" %>
		<%= f.text_field :load_combo %>
	</div>
	<div>
		<%= f.label "Mass Combination (MASSCOMBO):" %>
		<%= f.text_field :mass_combo %>
	</div>
	<div>
		<%= f.label "Ground Acceleration Multiplier (GAMULT):" %>
		<%= f.text_field :gamult %>
	</div> 
			
	<div class="action">
		<%= button_to "Save", load_option_path(@load_option.id) %>
	</div>
<% end %>	

app/views/load_options/edit.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-md-2 sidebar">
			<%= render :partial =>  "shared/nav" %>
		</div>

		<div class="col-md-10 col-md-offset-2 main">
			<% if params[:analysis_id] == nil %>
				<%= render :partial => "loadoption_default" %>
			<% else %>
				<%= render :partial => "loadoption_analysis" %>
			<% end %>
		</div>
	</div> 
</div>

app/views/load_options/show.html.erb
<% if params[:analysis_id] == nil %>
	<% edit_path = edit_load_option_path(@load_option.id) %>
	<% prev_path = vertical_constraint_option_path(current_default.vertical_constraint_option.id)%>
	<% next_path = response_time_history_option_path(current_default.response_time_history_option.id)%>
<% else %>
	<% edit_path = edit_model_analysis_default_load_option_path(current_model.id, current_analysis.id, current_default.id, @load_option.id) %>
	<% prev_path = model_analysis_default_vertical_constraint_option_path(current_model.id, current_analysis.id, current_default.id, current_default.vertical_constraint_option.id) %>
	<% next_path = model_analysis_default_response_time_history_option_path(current_model.id, current_analysis.id, current_default.id, current_default.response_time_history_option.id) %>
<% end %>

<div class="container-fluid">
	<div class="row">
		<div class="col-md-2 sidebar">
			<%= render :partial => "shared/nav" %>
		</div>
		<div class="col-md-10 col-md-offset-2 main">
			<h3>Load Options</h3>
			<div class="field">
				<p>Load Combination (LOADCOMBO): <%= @load_option.load_combo %></p>
				<p>Mass Combination (MASSCOMBO): <%= @load_option.mass_combo %></p>
				<p>Ground Acceleration Multiplier (GAMULT): <%= @load_option.gamult %></p>
			</div>
			<div class="action">
				<%= link_to "edit", edit_path %>
			</div>
			<%= button_to "Previous", prev_path, :method => :get%>
			<%= button_to "Next", next_path, :method => :get%>
		</div>
	</div> 
</div>